# Site settings
title: Aditya S. Pendyala
email: apendyal@stevens.edu
url: https://whitecanvasgypsy.github.io
description: "Aditya S. Pendyala - A technical writer, author, programmer, and analyst, currently on the rickety journey of job searching and the many perks that come with it; such as the pursuit of an amazing-looking portfolio website, comparable to the website that this text is displayed on."
keywords: "programmer, analyst, technical writer, content writer, author, entrepreneur, creative, user documentation, doctohelp, software design, software development, robohelp, fiction, end user guide, software documentation, illustrator, dreamweaver, programming, java, html, css, sql, python, tableau"
skills: "Technical Writer - Author - Programmer - Analyst"
meta_author: Pendyala Aditya

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Aditya

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Aditya Pendyala
  location: Hoboken, New Jersey
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/aditya-pendyala/
  - title: github
    url: http://github.com/whitecanvasgypsy

# Postal address (add as many lines as necessary)
address:
  - line: Hoboken
  - line: New Jersey, 07030

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
